### ISSUE TITLE
upgrade react version and other dependencies in package.json

### ISSUE THREAD

**Issue by danger-ahead** [GDSC-RCCIIT/website#1]
Currently we are using an old react version along with some other dependencies. We would like this to be upgrade to React 18. Also includes upgrading other dependencies as well.

**Comment by ShravaniAK** [comment]
i can do this , pl assign me this issue

**Comment by danger-ahead** [comment]
> i can do this , pl assign me this issue

Go ahead. Best of luck. Also remember to fix the syntax errors that might result from this upgrade.
