### ISSUE TITLE
Contribution.md

### ISSUE THREAD

**Issue by Olumarshal** [GDSC-RCCIIT/website#3]
Hi there, it would be nice to have a contributions.md guide to help people contribute to your project especially people new to open source. I would like to work on it if that's Ok.

**Comment by danger-ahead** [comment]
@Olumarshal go ahead. Do you have a template?

**Comment by Olumarshal** [comment]
Yes, i do have a template.

**Comment by danger-ahead** [comment]
> Yes, i do have a template.

mind sharing the link?
