### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by sb-decoder** [GDSC-RCCIIT/website#4]
I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file.

**Comment by danger-ahead** [comment]
@sb-decoder what do you want to update?

**Comment by Sowham-3098** [comment]
I want to add Code_of_conduct file and want to add contributer's profile images into readme file

**Comment by sb-decoder** [comment]
I want to add code_of_conduct.md file  and all contributers profile images into readme.md

**Comment by danger-ahead** [comment]
> I want to add code_of_conduct.md file and all contributers profile images into readme.md

and this addition of contributor profile images is going to be automated? like each time there's a new contributor, it gets added to readme?

**Comment by Sowham-3098** [comment]
Yeah!

**Comment by sb-decoder** [comment]
Yeah!

**Comment by danger-ahead** [comment]
Go ahead.
