### ISSUE TITLE
Migrating to React 18

### ISSUE THREAD

**Issue by danger-ahead** [GDSC-RCCIIT/website#6]
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead.
Until you switch to the new API, your app will behave as if it's running React 17.
Learn more: https://reactjs.org/link/switch-to-createroot
```
This a warning message in the console while running the app. Fix this.

**Comment by racky7** [comment]
@danger-ahead I want to work on this. Please assign it to me.

**Comment by danger-ahead** [comment]
> @danger-ahead I want to work on this. Please assign it to me.

Go ahead @racky7 ! Best of luck!
